### ISSUE TITLE
Can't use different direction variants of wood log on same "block space" in 1.20.1

### ISSUE THREAD

**Issue by MinecAncient** [CreativeMD/LittleTiles#1031]
I can not use different direction, orientation of log in MC 1.20.1 in the same block space. When i try it changing to the same type. 

example from MC 1.20.1
[
![obraz_2024-10-31_132633291](https://github.com/user-attachments/assets/771798df-f4c3-4821-a6ec-08fcff23e045)
](url)

example from MC 1.12.2
![Zrzut ekranu 2024-10-31 131617](https://github.com/user-attachments/assets/3853ade7-49a0-4d78-9fe1-38aeab9bfdef)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!

**Comment by MinecAncient** [comment]
Thanks for your fast answer and your afford. And i need to say it is not fixed.

**Comment by CreativeMD** [comment]
What exactly are you doing? Need more contest, because in my test it worked just fine (after my fix).

**Comment by MinecAncient** [comment]
![obraz_2024-11-12_162933603](https://github.com/user-attachments/assets/abba0d7b-a553-40fa-88fe-957e66a85d32) 

I want to mix different logs direction in the same block. There is a block and it is not possible to mix.

**Comment by CreativeMD** [comment]
Will be fixed in the next pre-release. Sorry there were multiple issues and I overlooked yours. New version is out for 1.20.1.

**Comment by MinecAncient** [comment]
Perfect :D Thank you, it is working :D
