### ISSUE TITLE
[1.21.1 Little Tiles Beta Pre161]Some issues I found

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/LittleTiles#1096]
1. When you change the gird from 1/x block to a full block, you will see it's a 1/2 block instead of a full block
2. There is an issue when you use "Slope" Tiles, they sometimes become a inner/outer slope when changing directions.
3. There is no color on the RGB.
4. The game crashes when you use Inner Slope/Outer Slope. (Crash log included).

[crash-2025-04-18_22.44.24-client.txt](https://github.com/user-attachments/files/19821349/crash-2025-04-18_22.44.24-client.txt)
[crash-2025-04-18_22.46.04-client.txt](https://github.com/user-attachments/files/19821350/crash-2025-04-18_22.46.04-client.txt)

https://github.com/user-attachments/assets/c9791165-db65-4ad9-b5aa-757b09435982

**Comment by ElderNym** [comment]
I've noticed 1,2, and 4, as well. 

For #3, did you mean no _alpha_ "color on the RGB"? I was trying to figure out how to apply transparency like I saw on videos, and it simply isn't there for me.

**Comment by Doc-1** [comment]
> For [#3](https://github.com/CreativeMD/LittleTiles/issues/3), did you mean no _alpha_ "color on the RGB"? I was trying to figure out how to apply transparency like I saw on videos, and it simply isn't there for me.

I think they are talking about how the sliders themselves used to have a color gradient as its background.

**Comment by CreativeMD** [comment]
All of them are fixed in the newest version. Make sure to update CreativeCore as well. Thanks a lot for reporting this issues. Sorry for my late response.

**Comment by voxpop9** [comment]
> All of them are fixed in the newest version. Make sure to update CreativeCore as well. Thanks a lot for reporting this issues. Sorry for my late response.

Slope rotation is still not fixed on Beta Pre163, CreativeCore 2.13.5. Sodium and Iris are installed.

![Image](https://github.com/user-attachments/assets/8c946e5a-7a94-42a0-b0ca-9c921dec37a2)
![Image](https://github.com/user-attachments/assets/3d999569-c46a-4b58-8720-d876d1919aba)
