### ISSUE TITLE
1.21.1 NeoForge Youer server blocks (tiles) placing issue with WorldGuard plugin

### ISSUE THREAD

**Issue by overfounder** [CreativeMD/LittleTiles#1116]
I decided to create a separate topic because the problem is also present on the most current and still supported NeoForge version of mod.

“Tiles” or structures/ blocks from mod can be placed in another player’s region on server (WorldGuard plugin), without permission.

There's no problem with Little Tiles microblocks/structures cannot be broken in someone’s region (this works normally), and accordingly you cannot edit/break any blocks by applying on them little tiles functions, as it should be.

Problem is that they can be placed by any player, like if the region did not exist at all, and only placing (without breaking, replacing) of tiles structures ignores region’s restrictions. Because normal minecraft blocks (also from mods) can’t be normally placed in region if permission is not given and can if this is allowed, so little tiles just fully ignores placing restrictions.
And no matter what method of placing structures is used, like placing little workbench, little blueprint, placing tiles with little chisel, placing ready-made structure from inventory and etc. (excluding methods that edit/break already placed blocks in region with restrictions).

Maybe have any ideas how to fix it? 
We already tried (and still trying), but so far there are no significant results.
Also would be awesome if the problem was fixed in mod updates, of course if possible. Because it does not allow to install mod on many servers.

Minecraft 1.21.1 NeoForge Youer (MohistMc/Youer - newest NeoForge Hybrid server implementing the Spigot/Bukkit API). 
Pre165 version of LittleTiles.

**Comment by CreativeMD** [comment]
Ok, so the problem appears was not the actual removal part which was not protected. The issue was that the client did not receive a reset packet. Which means the blocks stayed modified on client (visual glitch). Fixed in 1.21.1. Thanks for reporting this issue.

**Comment by overfounder** [comment]
Problem is still here, it’s not just a visual problem. Tiles just can be placed in protected area, everyone can place and see it. And interesting that they can’t be broken, so they are somehow defined as blocks and protected from editing and destroying. We spent several hours trying to fix it ourselves, also to «embed plugin into mod», but we couldn't.
