### ISSUE TITLE
Littletiles assets disappear seemingly at random

### ISSUE THREAD

**Issue by tolerus** [CreativeMD/LittleTiles#567]
Hi!

Great job on the new release; can't wait to get started with the new particle system and redstone options!

We've been having an issue with our Littletiles structures disappearing. It seems to happen a lot especially around dusk and at night and it also never seems to effect anything underground. This has me wondering if it has something to do with lighting? It all comes back when we reload the game but it happens pretty frequently. Playing on a local server. Some of us have shaders and some do not; it effects all players regardless.

Here are screenshots
[https://imgur.com/a/ajc8RdN](url)

Mods installed:
`Client attempting to join with 56 mods : quarkoddities@1,gardenstuff@1.12-2.1.1,dynamictreesbop@1.12.2-1.4.4,creativecoredummy@1.0.0,extrabitmanipulation@1.12.2-3.4.1,animania@2.0.0.23,locks@2.2.1,dynamictreesquark@1.12.2-1.0.6,jei@4.15.0.291,bibliocraft@2.4.5,craftstudioapi@1.0.0,mcp@9.42,ctm@MC1.12.2-1.0.2.31,chameleon@1.12-4.1.3,forgelin@1.8.2,xreliquary@1.12.2-1.3.4.786,stg@1.12.2-1.2.3,foamfixcore@7.7.4,joypadsplitscreenmod@1.12.0-0.22,carryon@1.12.1,mcmultipart@2.5.3,forge@14.23.5.2854,testdummy@1.12,storagedrawersextra@@VERSION@,worldgenerationprofiler@1.2.1.5,variedcommodities@1.12.2,minecraft@1.12.2,pecunia_mod@1.3,theoneprobe@1.4.28,biomesoplenty@7.0.1.2444,customstuff4@0.5.3,opticmanager@1.0,creativecore@1.10.0,littleopener@1.0.1,fairylights@2.1.10,astikorcarts@1.12.2-0.1.2.7,littletilescore@1.0.0,vanillafix@1.0.10-SNAPSHOT,quark@r1.6-179,autoreglib@1.3-32,storagedrawers@1.12-5.3.5,FML@8.0.99.99,dimdoors@3.0.9+287,customnpcs@1.12,edxmultipart@1.1.1,worldedit@6.1.10-SNAPSHOT,opframe@1.4.0,chisel@MC1.12.2-1.0.2.45,foamfix@0.10.5-1.12.2,forgeessentialsclient@12.3,impart@1.12.2,vtt@0.6.4,chiselsandbits@14.30,dynamictrees@1.12.2-0.9.21,playerrevive@1.0,littletiles@1.5.0`

Latest log:
[https://pastebin.com/Vp2bDMmr](url)

**Comment by CreativeMD** [comment]
If Optifine is installed make sure render regions are turned off.

**Comment by tolerus** [comment]
Thanks for the tip - 
Optifine is indeed installed and render regions had already been turned off for all players.

Getting crashes now, too. Here's the latest:
[https://pastebin.com/1MswrhTL](url)

**Comment by CreativeMD** [comment]
Should also be fixed in the newest version. Just update and let me know if it works.

**Comment by tolerus** [comment]
Updated Littletiles and CreativeCore and the problem is still there...

**Comment by CreativeMD** [comment]
Does it crash with pre310? Or are block still disappearing? Would need the new log then.

**Comment by tolerus** [comment]
Blocks are disappearing with pre310. Haven't had a crash in a while -
although now that you mention it we did have a crash trying to view a
recipe for the particle emitter in JEI. Here's a recent log

https://pastebin.com/ztQwawG2

And here is the crash

https://pastebin.com/adMKf6WY

**Comment by tolerus** [comment]
It seems like we can force blocks to disappear every time when we have a
block from another mod that's running some sort of process (e.g. when
Animania's cheese mold is processing) in the same chunk. Then all of the
littletiles blocks in that chunk disappear-- although strangely only the
blocks that are above ground???

**Comment by tolerus** [comment]
Here's the player log from a session that I know that the blocks were having a lot of problems staying loaded. To get them to reload we just make an arbitrary change to any video setting that forces the blocks to reload, or restart the game

Log split into 2 pastebins:
[https://pastebin.com/LVJiddKw](url)
[https://pastebin.com/ZYwnNbpF](url)

**Comment by tolerus** [comment]
Here are logs from a short session that I just started up in order to get the glitch to happen:

Player log:
[https://pastebin.com/tgJpHShU](url)

Server log:
[https://pastebin.com/07Y5khU0](url)

Screenshots:
[https://imgur.com/a/VEBlaPl](url)

**Comment by CreativeMD** [comment]
Sorry, but could you please link your stuff differently. Each of your links does not work, I have copy paste it in the url bar. Just copy the links in there and don't do anything with it. Thanks! Will look into it soon.

**Comment by tolerus** [comment]
Sure thing!
Here are logs from a short session that I just started up in order to get the glitch to happen:

Player log:
https://pastebin.com/tgJpHShU

Server log:
https://pastebin.com/07Y5khU0

Screenshots:
https://imgur.com/a/VEBlaPl

**Comment by CreativeMD** [comment]
Might be fixed in the newest version.

**Comment by tolerus** [comment]
This is fixed! Excellent - great job!

Additionally I was going to mention that we can't place non-LittleTiles
blocks on top of any existing LittleTiles blocks but you seem to have fix
all of that too before I could even say anything.

This is great!! Thanks!

**Comment by CreativeMD** [comment]
That's lovely to hear! Very happy this could finally be solved.
