### ISSUE TITLE
Signal Converter Errors and Crash

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#569]
Placing and removing cables near the signal converter I get the error shown below. 
[Placing And Breaking error.txt](https://github.com/CreativeMD/LittleTiles/files/5802216/Placing.And.Breaking.error.txt)

Then if I attempt to send a signal to the converter I get the crash report below.
[crash-2021-01-12_07.56.05-server.txt](https://github.com/CreativeMD/LittleTiles/files/5802221/crash-2021-01-12_07.56.05-server.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest pre-release. Thanks for reporting this issue!

**Comment by Doc-1** [comment]
Its not the same error however, I and another person on discord, Hiru, still crashes when a signal is sent to it but unfortently we don't have the same crashes. I even get two different crashes during my tests. We both have the latest versions LT pre318, and CC v1.10.44. Lastly, I am able to use the Signal Converter in the dev enviroment just fine. Only when it is compiled is there a issue. I've provided the crash that Hiru submitted on discord as well to keep it all in one place. 
Mine, Abstract World
[crash-2021-01-22_11.39.23-server.txt](https://github.com/CreativeMD/LittleTiles/files/5857259/crash-2021-01-22_11.39.23-server.txt)
Mine, No ClassDef Error.
[crash-2021-01-22_11.29.38-server.txt](https://github.com/CreativeMD/LittleTiles/files/5857266/crash-2021-01-22_11.29.38-server.txt)
Hiru, Index out of bounds
[crash-2021-01-22_13.05.55-server.txt](https://github.com/CreativeMD/LittleTiles/files/5857281/crash-2021-01-22_13.05.55-server.txt)

**Comment by CreativeMD** [comment]
Please open a new issue for that.
