### ISSUE TITLE
Door Closes on first right click, Undoing an open door swaps bit values

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#570]
Having a door activator with input and output with the settings of:
b0 : i1
Toggle delay: 1
o2 : b0
Equal delay: 1
Will make the door close the first time you open it. If you change b0 : i1 to Equal it will close every time you open it. It seems like it is acting as though o2 is connected to i1. 

After opening a door, breaking it, then bringing it back with undo will set b0 to 1. Now being close is 1 and open is 0.

![door](https://user-images.githubusercontent.com/45431412/104340367-9da49980-54c6-11eb-8355-ed26991bd87a.gif)

Here is an export of the door used in the gif.
[testdoor.txt](https://github.com/CreativeMD/LittleTiles/files/5803307/testdoor.txt)

**Comment by CreativeMD** [comment]
I hope this is also fixed in the newest version, if not just let me know here!

**Comment by Doc-1** [comment]
Just tried it with LT pre307 and CC v1.10.41 and both issues still occur.

**Comment by CreativeMD** [comment]
Is finally fixed in the newest version of LittleTiles.
