### ISSUE TITLE
clicking on structure which is entity may also interact with blocks behind it

### ISSUE THREAD

**Issue by Vodulm** [CreativeMD/LittleTiles#591]
https://vimeo.com/507350676

**Comment by CreativeMD** [comment]
Fixed in the newest version.

**Comment by Vodulm** [comment]
As of v1.5.15 it still happens:
![2021-07-10_19 12 36](https://user-images.githubusercontent.com/73194834/125170012-86b0dc80-e1b5-11eb-9bc2-3843b11fc604.png)
![2021-07-10_19 12 39](https://user-images.githubusercontent.com/73194834/125170013-87497300-e1b5-11eb-8b55-17df9b3b705f.png)


Also, when opening a door it places a block:
![2021-07-10_19 12 03](https://user-images.githubusercontent.com/73194834/125170070-cb3c7800-e1b5-11eb-8715-ddf0568262fb.png)
![2021-07-10_19 12 07](https://user-images.githubusercontent.com/73194834/125170072-cc6da500-e1b5-11eb-87e5-0b716dc415a7.png)

**Comment by CreativeMD** [comment]
Thanks for reporting it. Fixed in the newest version.
