### ISSUE TITLE
Door Issues

### ISSUE THREAD

**Issue by Doc-1** [CreativeMD/LittleTiles#605]
I was testing things on the server-side and noticed that the doors are not syncing correctly. If you want the world download or a copy of the door structure, please let me know. Thank you.
The things I did:
- The door is set to stay animated
- The door opens/closes automatically with signalings.
- Player on the right side teleported there first, then the player on the left.
![Doors and server](https://user-images.githubusercontent.com/45431412/111091902-d08cfd00-850a-11eb-8704-ec6eebc1358a.gif)

**Comment by CreativeMD** [comment]
Yes send me your world, so I can try to reproduce it, looks like either the client or the server missed one packet.

**Comment by Doc-1** [comment]
I just attempted it again a few times and turns out it only occurs when the door loop is set in a door activator. It does not occur when the door loop is in the door itself. The world it is placed in does not change it.
The export does have an input but does not need any signal. Sometimes it doesn't start right away.

[Syncing Issue Door.txt](https://github.com/CreativeMD/LittleTiles/files/6287532/Syncing.Issue.Door.txt)

**Comment by CreativeMD** [comment]
I can't really reproduce it with just the structure. Is there a way to get the world?

**Comment by Doc-1** [comment]
Can do, will send it to you later over Discord.

**Comment by CreativeMD** [comment]
After so many people have reported issues related to doors over and over again, I finally decided to rework the system.
@Doc-1, @Masher414, @x3415, @thecheesemo, @oniison, @juh9870

Please test this new version and post your results here.

NOTE: This is not compatible with ALET yet.

https://www.dropbox.com/s/8j97pccjzv1qyfn/CreativeCore_v1.10.66_mc1.12.2.jar?dl=1
https://www.dropbox.com/s/afxkg1vqr7cohwa/LittleTiles_v1.5.36_mc1.12.2.jar?dl=1
https://www.dropbox.com/s/6pfjfyzgn3mmz4j/LittleFrames_v1.0.11_mc1.12.2.jar?dl=1

**Comment by juh9870** [comment]
@CreativeMD
[crash-2021-11-05_20.09.00-client.txt](https://github.com/CreativeMD/LittleTiles/files/7488092/crash-2021-11-05_20.09.00-client.txt)
[crash-2021-11-05_20.10.28-client.txt](https://github.com/CreativeMD/LittleTiles/files/7488097/crash-2021-11-05_20.10.28-client.txt)

crash upon opening and closing a door a few times.
Also glitched parts are still here
![2021-11-05_20 10 25](https://user-images.githubusercontent.com/15922601/140558559-812539dc-c834-457f-8347-062c4f0e13b3.png)
![2021-11-05_20 10 08](https://user-images.githubusercontent.com/15922601/140558566-9514c1ef-79bf-4873-adfa-12769b03554a.png)
![2021-11-05_20 10 17](https://user-images.githubusercontent.com/15922601/140558571-aff7a1bb-2f3b-4817-9699-b85b5a70af0f.png)
![2021-11-05_20 10 21](https://user-images.githubusercontent.com/15922601/140558574-1c399363-8b1e-4f14-b013-dddc7fdd3593.png)

**Comment by Doc-1** [comment]
Using the latest pulled version on GitHub, the issue I reported is fixed. The doors stay synced for both clients. However, breaking the door as an entity does not sync. So if client_1 breaks the entity door, client_2 still sees the entity.

**Comment by CreativeMD** [comment]
@juh9870 this should fix your crash. Just a note to remember. This update does not fix doors that are already broken, it aims to fix that something like this happens in the first place (pretty sure you placed a new door, I just want to make sure)

@Doc-1 your issue should be fixed as well.

https://www.dropbox.com/s/h7ekp3pbvpb98i4/CreativeCore_v1.10.67_mc1.12.2.jar?dl=1
https://www.dropbox.com/s/83a1dkhlxbb1epk/LittleTiles_v1.5.39_mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
Ok fixed even more issues.

@juh9870 your door should work now, but I highly recommend to build a frame around it and make one door activator which activates all 8 parts, instead of making each part depend on the other one. This will improve performance and get rid of the flickering.

https://www.dropbox.com/s/835u6xys81m55wx/LittleTiles_v1.5.40_mc1.12.2.jar?dl=1

From what I can tell this is kind of stable. So if there are no new issues reported I will release it soon.

**Comment by CreativeMD** [comment]
Ok, more updates ... there was an issue with blocks getting lost.

https://www.dropbox.com/s/1wbowt6c6gk1102/CreativeCore_v1.10.68_mc1.12.2.jar?dl=1
https://www.dropbox.com/s/1dpb9m86dw8mk4c/LittleTiles_v1.5.43_mc1.12.2.jar?dl=1
https://www.dropbox.com/s/bj42dm30trx57vm/LittleFrames_v1.0.12_mc1.12.2.jar?dl=1

**Comment by Doc-1** [comment]
Yup, that fixed the issue of the door breaking not syncing.

**Comment by CreativeMD** [comment]
Released the update. Just open new issues if there are still issues.
