### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 192

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleTiles#737]
java.lang.ArrayIndexOutOfBoundsException: 192
	at com.creativemd.littletiles.common.tile.LittleTile.fillInSpace(LittleTile.java:227)
	at com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles.convertBlockToVanilla(TileEntityLittleTiles.java:314)
	at com.creativemd.littletiles.common.action.block.LittleActionPlaceAbsolute.action(LittleActionPlaceAbsolute.java:99)
	at com.creativemd.littletiles.common.action.LittleActionCombined.action(LittleActionCombined.java:47)
	at com.creativemd.littletiles.common.action.LittleAction.undo(LittleAction.java:143)
	at com.creativemd.littletiles.client.render.overlay.PreviewRenderer.handleUndoAndRedo(PreviewRenderer.java:79)
	at com.creativemd.littletiles.client.render.overlay.PreviewRenderer.tick(PreviewRenderer.java:111)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_411_PreviewRenderer_tick_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1959)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

When I want to put a little frame in overwrite mode into a block and then undo it, there is this crash.

**Comment by yusuf72100** [comment]
i have the same problem but i can't seem to fix it !

help PLEASE

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!

**Comment by yusuf72100** [comment]
I still have this problem :/

Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(4) exceeds writerIndex(10): UnpooledSlicedByteBuf(ridx: 9, widx: 10, cap: 10/10, unwrapped: PooledUnsafeDirectByteBuf(ridx: 0, widx: 11, cap: 11))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:766) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at com.creativemd.creativecore.common.packet.CreativeCorePacket.readPos(CreativeCorePacket.java:77) ~[CreativeCorePacket.class:?]
	at com.creativemd.littletiles.common.packet.LittleBlockPacket.readBytes(LittleBlockPacket.java:191) ~[LittleBlockPacket.class:?]
	at com.creativemd.creativecore.common.packet.CreativeMessageHandler.fromBytes(CreativeMessageHandler.java:46) ~[CreativeMessageHandler.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:36) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:26) ~[SimpleIndexedCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:111) ~[FMLIndexedMessageToMessageCodec.class:?]
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:41) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	... 57 more

And it give me an fatal error when i try to connect to my server but no crash:
[11:19:47] [Netty Client IO #3/ERROR] [FML]: Network Disconnect: A fatal error has occurred, this connection is terminated
